language: node_js
node_js:
  - 14.4.0
services:
  - docker
install:
  - echo "nothing needs to be installed locally"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging. Tip: Use different tags each time you push images to the Dockerhub.
  - docker tag udagram-api-feed danthedangerman/udagram-api-feed:v1
  - docker tag udagram-api-user danthedangerman/udagram-api-user:v1
  - docker tag udagram-frontend danthedangerman/udagram-frontend:v1
  - docker tag udagram-reverseproxy danthedangerman/udagram-reverseproxy:v1

  # Push# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danthedangerman/udagram-api-feed:v1
  - docker push danthedangerman/udagram-api-user:v1
  - docker push danthedangerman/udagram-frontend:v1
  - docker push danthedangerman/udagram-reverseproxy:v1
